3rd task
js-tasks-ru/htmlcss-20220210_daria-kuzina-e pull request #5
Opened 2022-02-18 11:15 UTC by Dzhakuzina

2022-02-18 11:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-20 16:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-12 19:03 UTC, GSemikozov requested changes

2022-03-12 19:03 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
помимо font-size надо и все остальные стили для описания текста добавить)

2022-03-12 19:03 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
и еще не хватает паддингов

2022-03-12 19:03 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +     cursor: pointer;
cursor + transition можно указать сразу на .btn, и на hover если что дублировать не надо

2022-03-12 19:03 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +      border: none;
ну уровне .btn уже обнулили бордеры

2022-03-12 19:03 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    .btn_primary_disabled {
вместо модификатора модификатора (с точки зрения БЭМ это само собой ошибка) мы будем использовать общее для всех типов кнопок состояние - .btn:disabled

2022-03-20 14:52 UTC, GSemikozov approved these changes

2022-03-20 14:52 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-03-20 14:55 UTC, GSemikozov approved these changes

2022-03-20 14:55 UTC, merged