4th task
js-tasks-ru/htmlcss-20220210_daria-kuzina-e pull request #7
Opened 2022-02-22 15:10 UTC by Dzhakuzina

/accordion/

2022-02-22 15:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-27 14:24 UTC, GSemikozov requested changes

2022-02-27 14:24 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import url(https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css);
глобальные штуки подключаем в общий файлах, в случае с нормалайз можно в main.css (если хотим через css)

2022-02-27 14:24 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +*{
про универсальный селектор, особенно в случае использования БЭМ, лучше забыть ;)

если хочется задать общие стили для текста внутри блока - можно в .accordion

2022-02-27 14:24 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +     margin: 8px;
наверное имелось в виду только margin-bottom?

2022-02-27 14:24 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +     width: 579px;
ширину лучше жестко не фиксировать, можно удалить

2022-02-27 14:24 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +     padding: 24px 419px 24px 32px;
справа какой-то огромный паддинг - на самом деле он должен быть такой же как слева

2022-02-27 14:24 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +     height: 168px;
фиксировать размеры блока в состоянии "открыто" будет оч плохо для UI - у нас ведь всегда будет разный контент внутри

2022-03-03 16:28 UTC, GSemikozov approved these changes

2022-03-03 16:28 UTC, merged